"""First-pass waveforms for the single-phase full-bridge inverter."""

from __future__ import annotations

import math

from ....models.operating_point import OperatingPoint
from ....models.waveform import WaveformSet
from ...base.candidate import TopologyCandidate
from .synthesizer import calculate_series_rl_open_loop_operating_point

TCM_DETAIL_SAMPLES_PER_CYCLE = 8
TCM_DETAIL_MAX_POINTS = 30_000
TCM_LOW_SLOPE_FSW_TOLERANCE = 0.999


def generate_waveforms(
    candidate: TopologyCandidate,
    operating_point: OperatingPoint | None = None,
) -> WaveformSet:
    """Generate one line cycle of inverter waveforms.

    The primary WaveformSet arrays remain the low-frequency engineering
    waveforms used by the current capacitor first-pass selector. A detailed
    unipolar-SPWM preview is attached in metadata for GUI waveform inspection.
    """

    if str(candidate.mode_capable).startswith("tcm_"):
        return _generate_tcm_envelope_waveforms(candidate, operating_point=operating_point)

    metadata = candidate.metadata
    load_ratio = _clamp_load_ratio(operating_point.load_ratio if operating_point is not None else 1.0)
    vdc_v = float(metadata["vdc_nom_v"])
    vac_rms_v = float(metadata["vac_rms_v"])
    vac_peak_v = float(metadata["vac_peak_v"])
    pout_w = float(candidate.pout_target)
    operating_power_factor = _operating_power_factor(operating_point, float(metadata["power_factor"]))
    pf_abs = _power_factor_abs_for_current(operating_power_factor)
    active_power_sign = _active_power_sign(operating_power_factor)
    requested_operating_pout_w = pout_w * load_ratio
    operating_contract = calculate_series_rl_open_loop_operating_point(
        vdc_nom_v=vdc_v,
        vac_rms_v=vac_rms_v,
        f_line_hz=float(metadata["f_line_hz"]),
        fsw_hz=float(metadata["fsw_hz"]),
        pout_w=max(requested_operating_pout_w, 1e-12),
        power_factor=pf_abs,
        output_inductance_h=float(candidate.inductance_h),
    )
    operating_pout_w = active_power_sign * float(operating_contract["achieved_output_active_power_w"])
    iac_rms_a = float(operating_contract["achieved_output_current_fundamental_rms_a"])
    iac_peak_a = math.sqrt(2.0) * iac_rms_a
    phi_rad = math.acos(float(operating_contract["bridge_current_displacement_power_factor"]))
    f_line_hz = float(metadata["f_line_hz"])
    fsw_hz = float(metadata["fsw_hz"])
    cdc_f = float(metadata["cdc_required_f"])
    idc_avg_a = operating_pout_w / max(vdc_v, 1e-12)
    samples = 720
    period_s = 1.0 / f_line_hz
    time_s: list[float] = []
    vout_v: list[float] = []
    iout_a: list[float] = []
    dc_cap_current_a: list[float] = []
    modulation: list[float] = []
    for index in range(samples + 1):
        t_s = period_s * index / samples
        theta = 2.0 * math.pi * f_line_hz * t_s
        vac = vac_peak_v * math.sin(theta)
        iac = active_power_sign * iac_peak_a * math.sin(theta - phi_rad)
        pac = vac * iac
        idc_inst = pac / max(vdc_v, 1e-12)
        time_s.append(t_s)
        vout_v.append(vac)
        iout_a.append(iac)
        dc_cap_current_a.append(idc_avg_a - idc_inst)
        modulation.append(vac / max(vdc_v, 1e-12))
    dc_cap_current_a = _remove_average(dc_cap_current_a)
    ripple_v = _integrate_periodic_capacitor_voltage(time_s, dc_cap_current_a, cdc_f)
    vdc_link_v = [vdc_v + value for value in ripple_v]
    refined = _build_refined_unipolar_spwm_waveforms(
        vdc_v=vdc_v,
        vac_peak_v=vac_peak_v,
        iac_peak_a=iac_peak_a,
        power_factor=operating_power_factor,
        f_line_hz=f_line_hz,
        fsw_hz=fsw_hz,
        inductance_h=float(operating_contract["validation_effective_series_inductance_h"]),
        capacitance_f=cdc_f,
        idc_avg_a=idc_avg_a,
        low_frequency_time_s=time_s,
        low_frequency_vdc_v=vdc_link_v,
    )
    return WaveformSet(
        time_s=time_s,
        switch_node_voltage_v=vout_v,
        inductor_current_a=iout_a,
        capacitor_current_a=dc_cap_current_a,
        output_voltage_v=vdc_link_v,
        operating_vin_v=vdc_v,
        operating_vout_v=float(operating_contract["achieved_output_voltage_fundamental_rms_v"]),
        duty=0.5,
        load_ratio=load_ratio,
        switching_period_s=1.0 / fsw_hz,
        time_span_s=period_s,
        inductor_current_min_a=min(iout_a),
        inductor_current_max_a=max(iout_a),
        mode="ccm unipolar SPWM refined preview",
        inductor_voltage_v=vout_v,
        output_ripple_v=ripple_v,
        notes=[
            "First-pass sine output and DC-link twice-line ripple waveform.",
            "Refined metadata includes unipolar-SPWM gate states, three-level bridge voltage, and PWM inductor-current ripple.",
            "DC-link voltage ripple is generated by integrating i_Cdc/Cdc over one line cycle and removing DC offset.",
            "Dead-time, nonlinear Coss trajectory, and device parasitic ringing are not modeled.",
        ],
        metadata={
            "modulation_index_waveform": modulation,
            "operating_power_factor": operating_power_factor,
            "operating_power_factor_abs_for_current": pf_abs,
            "requested_operating_active_power_w": active_power_sign * requested_operating_pout_w,
            "operating_active_power_w": operating_pout_w,
            "operating_iac_rms_a": iac_rms_a,
            "operating_iac_peak_a": iac_peak_a,
            "operating_idc_avg_a": idc_avg_a,
            "dc_link_voltage_ripple_pp_v": max(ripple_v) - min(ripple_v) if ripple_v else 0.0,
            "dc_link_capacitor_current_rms_a": _rms(dc_cap_current_a),
            "single_phase_inverter_refined_waveforms": refined,
            "refined_pwm_sample_count": len(refined["time_s"]),
            "refined_pwm_samples_per_switching_period": refined["samples_per_switching_period"],
            "refined_bridge_voltage_levels_v": refined["bridge_voltage_levels_v"],
            "refined_inductor_pwm_ripple_pp_a": refined["inductor_pwm_ripple_pp_a"],
            "refined_inductor_pwm_ripple_mean_local_pp_a": refined["inductor_pwm_ripple_mean_local_pp_a"],
            "refined_inductor_pwm_ripple_local_pp_rms_a": refined["inductor_pwm_ripple_local_pp_rms_a"],
            "refined_dc_link_capacitor_current_pwm_rms_a": refined["dc_link_capacitor_current_pwm_rms_a"],
            "refined_dc_link_voltage_pwm_ripple_pp_v": refined["dc_link_voltage_pwm_ripple_pp_v"],
            "single_phase_inverter_branch_currents": refined["branch_current_metrics"],
            **operating_contract,
        },
    )


def _generate_tcm_envelope_waveforms(
    candidate: TopologyCandidate,
    operating_point: OperatingPoint | None = None,
) -> WaveformSet:
    metadata = candidate.metadata
    load_ratio = _clamp_load_ratio(operating_point.load_ratio if operating_point is not None else 1.0)
    vdc_v = float(metadata["vdc_nom_v"])
    vac_rms_v = float(metadata["vac_rms_v"])
    vac_peak_v = float(metadata["vac_peak_v"])
    pout_w = float(candidate.pout_target)
    operating_power_factor = _operating_power_factor(operating_point, float(metadata["power_factor"]))
    pf_abs = _power_factor_abs_for_current(operating_power_factor)
    active_power_sign = _active_power_sign(operating_power_factor)
    operating_pout_w = active_power_sign * pout_w * load_ratio
    iac_rms_a = abs(operating_pout_w) / max(vac_rms_v * pf_abs, 1e-12)
    iac_peak_a = math.sqrt(2.0) * iac_rms_a
    phi_rad = _current_phase_rad(operating_power_factor)
    f_line_hz = float(metadata["f_line_hz"])
    cdc_f = float(metadata["cdc_required_f"])
    inductance_h = float(candidate.inductance_h)
    irev_abs_a = abs(float(metadata.get("tcm_valley_current_target_a", candidate.il_valley)))
    vac_floor_v = float(metadata.get("tcm_vac_floor_v", 0.02 * vac_peak_v))
    fsw_min_hz = float(metadata.get("fsw_min_hz", 0.0) or 0.0)
    idc_avg_a = operating_pout_w / max(vdc_v, 1e-12)
    samples = 720
    period_s = 1.0 / f_line_hz

    time_s: list[float] = []
    vout_v: list[float] = []
    iavg_a: list[float] = []
    ipeak_env_a: list[float] = []
    ivalley_env_a: list[float] = []
    delta_i_a: list[float] = []
    fsw_hz: list[float] = []
    t_up_s: list[float] = []
    t_down_s: list[float] = []
    dc_cap_current_a: list[float] = []
    modulation: list[float] = []
    for index in range(samples + 1):
        t_s = period_s * index / samples
        theta = 2.0 * math.pi * f_line_hz * t_s
        vac = vac_peak_v * math.sin(theta)
        avg = active_power_sign * iac_peak_a * math.sin(theta - phi_rad)
        state = _tcm_cycle_state(
            avg_a=avg,
            vac_v=vac,
            vdc_v=vdc_v,
            inductance_h=inductance_h,
            irev_abs_a=irev_abs_a,
            vac_floor_v=vac_floor_v,
            fsw_min_hz=fsw_min_hz,
        )
        pac = vac * avg
        idc_inst = pac / max(vdc_v, 1e-12)

        time_s.append(t_s)
        vout_v.append(vac)
        iavg_a.append(avg)
        ipeak_env_a.append(float(state["peak_signed_a"]))
        ivalley_env_a.append(float(state["valley_signed_a"]))
        delta_i_a.append(float(state["delta_i_a"]))
        fsw_hz.append(float(state["fsw_hz"]))
        t_up_s.append(float(state["t_up_s"]))
        t_down_s.append(float(state["t_down_s"]))
        dc_cap_current_a.append(idc_avg_a - idc_inst)
        modulation.append(vac / max(vdc_v, 1e-12))

    detail = _build_tcm_detail_current_waveform(
        vdc_v=vdc_v,
        vac_peak_v=vac_peak_v,
        iac_peak_a=iac_peak_a,
        active_power_sign=active_power_sign,
        phi_rad=phi_rad,
        f_line_hz=f_line_hz,
        inductance_h=inductance_h,
        irev_abs_a=irev_abs_a,
        vac_floor_v=vac_floor_v,
        fsw_min_hz=fsw_min_hz,
    )
    low_slope = _tcm_low_slope_diagnostic(
        detail,
        fsw_min_hz=fsw_min_hz,
    )
    dc_cap_current_a = _remove_average(dc_cap_current_a)
    tcm_dc_link_detail = _build_tcm_dc_link_capacitor_current_detail(
        detail_time_s=[float(value) for value in detail["time_s"]],
        detail_inductor_current_a=[float(value) for value in detail["inductor_current_a"]],
        vac_peak_v=vac_peak_v,
        f_line_hz=f_line_hz,
        idc_avg_a=idc_avg_a,
        vdc_v=vdc_v,
    )
    ripple_v = _integrate_periodic_capacitor_voltage(time_s, dc_cap_current_a, cdc_f)
    vdc_link_v = [vdc_v + value for value in ripple_v]
    notes = [
        "First-pass TCM waveform with triangular current reconstruction; switching transitions and gate states are not modeled.",
        "Detailed TCM current is a triangular reconstruction for visualization; switching transitions and parasitics are not modeled.",
        "Peak and valley traces show the signed triangular-current envelope using the fixed negative valley-current target.",
        "DC-link voltage ripple is generated from the low-frequency power-balance capacitor current.",
        "TCM high-frequency triangular-current DC-link RMS is available for capacitor selection as a first-pass instantaneous-power proxy.",
        "Real bridge dc-bus pulse shape, dead-time, nonlinear Coss trajectory, parasitic ringing, and harmonic ESR correction are not modeled.",
    ]
    if low_slope["low_slope_region_detected"]:
        notes.append(
            "TCM low-slope region detected: mixed-mode fallback clamps switching frequency to fsw_min and relaxes the fixed valley-current target."
        )
    return WaveformSet(
        time_s=time_s,
        switch_node_voltage_v=vout_v,
        inductor_current_a=iavg_a,
        capacitor_current_a=dc_cap_current_a,
        output_voltage_v=vdc_link_v,
        operating_vin_v=vdc_v,
        operating_vout_v=vac_rms_v,
        duty=0.5,
        load_ratio=load_ratio,
        switching_period_s=1.0 / max(_mean(fsw_hz), 1e-12),
        time_span_s=period_s,
        inductor_current_min_a=min(min(iavg_a), min(ipeak_env_a), min(ivalley_env_a)),
        inductor_current_max_a=max(max(iavg_a), max(ipeak_env_a), max(ivalley_env_a)),
        mode="tcm triangular-current envelope",
        inductor_voltage_v=vout_v,
        output_ripple_v=ripple_v,
        notes=notes,
        metadata={
            "modulation_index_waveform": modulation,
            "operating_power_factor": operating_power_factor,
            "operating_power_factor_abs_for_current": pf_abs,
            "operating_active_power_w": operating_pout_w,
            "operating_iac_rms_a": iac_rms_a,
            "operating_iac_peak_a": iac_peak_a,
            "operating_idc_avg_a": idc_avg_a,
            "dc_link_voltage_ripple_pp_v": max(ripple_v) - min(ripple_v) if ripple_v else 0.0,
            "dc_link_capacitor_current_rms_a": _rms(dc_cap_current_a),
            "single_phase_inverter_tcm_envelope": {
                "time_s": time_s,
                "vac_fundamental_v": vout_v,
                "iavg_a": iavg_a,
                "ipeak_envelope_a": ipeak_env_a,
                "ivalley_envelope_a": ivalley_env_a,
                "delta_i_a": delta_i_a,
                "fsw_hz": fsw_hz,
                "t_up_s": t_up_s,
                "t_down_s": t_down_s,
                "detail_time_s": detail["time_s"],
                "detail_inductor_current_a": detail["inductor_current_a"],
                "detail_iavg_a": detail["iavg_a"],
                "detail_ipeak_envelope_a": detail["ipeak_envelope_a"],
                "detail_ivalley_envelope_a": detail["ivalley_envelope_a"],
                "detail_fsw_hz": detail["fsw_hz"],
                "detail_natural_fsw_hz": detail["natural_fsw_hz"],
                "detail_mixed_mode_clamped": detail["mixed_mode_clamped"],
                "detail_cycle_start_time_s": detail["cycle_start_time_s"],
                "detail_cycle_fsw_hz": detail["cycle_fsw_hz"],
                "detail_cycle_natural_fsw_hz": detail["cycle_natural_fsw_hz"],
                "detail_cycle_mixed_mode_clamped": detail["cycle_mixed_mode_clamped"],
                "detail_sample_count": detail["sample_count"],
                "detail_cycle_count": detail["cycle_count"],
                "detail_mixed_mode_cycle_count": detail["mixed_mode_cycle_count"],
                "detail_downsampled": detail["downsampled"],
                "samples_per_tcm_cycle": detail["samples_per_tcm_cycle"],
                "low_slope_diagnostic": low_slope,
                "dc_link_voltage_v": vdc_link_v,
                "dc_link_capacitor_current_a": dc_cap_current_a,
                "dc_link_capacitor_current_detail_time_s": tcm_dc_link_detail["time_s"],
                "dc_link_capacitor_current_detail_a": tcm_dc_link_detail["current_a"],
                "dc_link_capacitor_current_detail_rms_a": tcm_dc_link_detail["rms_a"],
                "dc_link_capacitor_current_low_frequency_rms_a": _rms(dc_cap_current_a),
                "dc_link_capacitor_current_basis": tcm_dc_link_detail["basis"],
                "notes": [
                    "TCM envelope is midpoint-free sampled over one line cycle for GUI inspection.",
                    "TCM detailed inductor current is a first-pass triangular reconstruction, not a transition/parasitic simulation.",
                    "Switching frequency is recomputed from fixed Lout and the operating load/PF current envelope.",
                    "TCM DC-link capacitor detail current uses instantaneous power v_ac*i_L_detail/Vdc and is an RMS proxy, not a harmonic ESR model.",
                    *(
                        [
                            "Low-slope TCM region uses mixed-mode fallback: fsw is clamped to fsw_min and fixed valley current is relaxed."
                        ]
                        if low_slope["low_slope_region_detected"]
                        else []
                    ),
                ],
            },
            "tcm_detail_time_s": detail["time_s"],
            "tcm_detail_inductor_current_a": detail["inductor_current_a"],
            "tcm_detail_sample_count": detail["sample_count"],
            "tcm_detail_cycle_count": detail["cycle_count"],
            "tcm_detail_downsampled": detail["downsampled"],
            "tcm_detail_iavg_a": detail["iavg_a"],
            "tcm_detail_ipeak_envelope_a": detail["ipeak_envelope_a"],
            "tcm_detail_ivalley_envelope_a": detail["ivalley_envelope_a"],
            "tcm_detail_fsw_hz": detail["fsw_hz"],
            "tcm_detail_natural_fsw_hz": detail["natural_fsw_hz"],
            "tcm_detail_mixed_mode_clamped": detail["mixed_mode_clamped"],
            "tcm_dc_link_capacitor_current_detail_time_s": tcm_dc_link_detail["time_s"],
            "tcm_dc_link_capacitor_current_detail_a": tcm_dc_link_detail["current_a"],
            "tcm_dc_link_capacitor_current_detail_rms_a": tcm_dc_link_detail["rms_a"],
            "tcm_dc_link_capacitor_current_low_frequency_rms_a": _rms(dc_cap_current_a),
            "tcm_dc_link_capacitor_current_basis": tcm_dc_link_detail["basis"],
            "tcm_time_s": time_s,
            "tcm_iavg_a": iavg_a,
            "tcm_ipeak_envelope_a": ipeak_env_a,
            "tcm_ivalley_envelope_a": ivalley_env_a,
            "tcm_delta_i_a": delta_i_a,
            "tcm_fsw_hz": fsw_hz,
            "tcm_t_up_s": t_up_s,
            "tcm_t_down_s": t_down_s,
            "tcm_fsw_min_actual_hz": min(fsw_hz),
            "tcm_fsw_max_actual_hz": max(fsw_hz),
            "tcm_detail_fsw_min_hz": min(detail["cycle_fsw_hz"]) if detail["cycle_fsw_hz"] else min(fsw_hz),
            "tcm_detail_fsw_max_hz": max(detail["cycle_fsw_hz"]) if detail["cycle_fsw_hz"] else max(fsw_hz),
            "tcm_detail_natural_fsw_min_hz": min(detail["cycle_natural_fsw_hz"]) if detail["cycle_natural_fsw_hz"] else min(fsw_hz),
            "tcm_detail_natural_fsw_max_hz": max(detail["cycle_natural_fsw_hz"]) if detail["cycle_natural_fsw_hz"] else max(fsw_hz),
            "tcm_low_slope_region_detected": low_slope["low_slope_region_detected"],
            "tcm_low_slope_fsw_min_limit_hz": low_slope["fsw_min_limit_hz"],
            "tcm_low_slope_min_fsw_hz": low_slope["min_fsw_hz"],
            "tcm_low_slope_min_fsw_time_s": low_slope["min_fsw_time_s"],
            "tcm_low_slope_violation_count": low_slope["violation_count"],
            "tcm_low_slope_cycle_count": low_slope["cycle_count"],
            "tcm_low_slope_violation_fraction": low_slope["violation_fraction"],
            "tcm_low_slope_mixed_mode_pending": False,
            "tcm_mixed_mode_fallback_active": low_slope["mixed_mode_fallback_active"],
            "tcm_mixed_mode_cycle_count": low_slope["violation_count"],
            "tcm_mixed_mode_cycle_fraction": low_slope["violation_fraction"],
        },
    )


def _build_tcm_detail_current_waveform(
    *,
    vdc_v: float,
    vac_peak_v: float,
    iac_peak_a: float,
    active_power_sign: float,
    phi_rad: float,
    f_line_hz: float,
    inductance_h: float,
    irev_abs_a: float,
    vac_floor_v: float,
    fsw_min_hz: float,
    samples_per_cycle: int = TCM_DETAIL_SAMPLES_PER_CYCLE,
    max_points: int = TCM_DETAIL_MAX_POINTS,
) -> dict[str, object]:
    period_s = 1.0 / max(f_line_hz, 1e-12)
    time_s: list[float] = []
    current_a: list[float] = []
    iavg_a: list[float] = []
    ipeak_envelope_a: list[float] = []
    ivalley_envelope_a: list[float] = []
    fsw_hz: list[float] = []
    natural_fsw_hz: list[float] = []
    mixed_mode_clamped: list[bool] = []
    cycle_start_time_s: list[float] = []
    cycle_fsw_hz: list[float] = []
    cycle_natural_fsw_hz: list[float] = []
    cycle_mixed_mode_clamped: list[bool] = []
    t_s = 0.0
    cycle_count = 0
    samples_per_cycle = max(int(samples_per_cycle), 4)

    while t_s < period_s:
        theta = 2.0 * math.pi * f_line_hz * t_s
        vac = vac_peak_v * math.sin(theta)
        avg = active_power_sign * iac_peak_a * math.sin(theta - phi_rad)
        state = _tcm_cycle_state(
            avg_a=avg,
            vac_v=vac,
            vdc_v=vdc_v,
            inductance_h=inductance_h,
            irev_abs_a=irev_abs_a,
            vac_floor_v=vac_floor_v,
            fsw_min_hz=fsw_min_hz,
        )
        valley_signed = float(state["valley_signed_a"])
        peak_signed = float(state["peak_signed_a"])
        t_up_s = float(state["t_up_s"])
        t_down_s = float(state["t_down_s"])
        switching_period_s = float(state["switching_period_s"])
        if switching_period_s <= 0.0:
            break
        cycle_fsw = float(state["fsw_hz"])
        cycle_natural_fsw = float(state["natural_fsw_hz"])
        clamped = bool(state["mixed_mode_clamped"])
        up_points = max(2, int(round(samples_per_cycle * t_up_s / switching_period_s)))
        down_points = max(2, samples_per_cycle - up_points + 1)
        cycle_start_time_s.append(t_s)
        cycle_fsw_hz.append(cycle_fsw)
        cycle_natural_fsw_hz.append(cycle_natural_fsw)
        cycle_mixed_mode_clamped.append(clamped)

        for point in range(up_points):
            fraction = point / max(up_points - 1, 1)
            sample_t = min(t_s + fraction * t_up_s, period_s)
            if time_s and time_s[-1] >= period_s and sample_t >= period_s:
                break
            sample_i = valley_signed + fraction * (peak_signed - valley_signed)
            _append_tcm_detail_sample(
                time_s,
                current_a,
                iavg_a,
                ipeak_envelope_a,
                ivalley_envelope_a,
                fsw_hz,
                natural_fsw_hz,
                mixed_mode_clamped,
                sample_t,
                sample_i,
                avg,
                peak_signed,
                valley_signed,
                cycle_fsw,
                cycle_natural_fsw,
                clamped,
            )
        for point in range(1, down_points):
            fraction = point / max(down_points - 1, 1)
            sample_t = min(t_s + t_up_s + fraction * t_down_s, period_s)
            if time_s and time_s[-1] >= period_s and sample_t >= period_s:
                break
            sample_i = peak_signed + fraction * (valley_signed - peak_signed)
            _append_tcm_detail_sample(
                time_s,
                current_a,
                iavg_a,
                ipeak_envelope_a,
                ivalley_envelope_a,
                fsw_hz,
                natural_fsw_hz,
                mixed_mode_clamped,
                sample_t,
                sample_i,
                avg,
                peak_signed,
                valley_signed,
                cycle_fsw,
                cycle_natural_fsw,
                clamped,
            )

        cycle_count += 1
        t_s += switching_period_s

    if not time_s or time_s[-1] < period_s:
        final_t = period_s
        theta = 2.0 * math.pi * f_line_hz * final_t
        vac = vac_peak_v * math.sin(theta)
        avg = active_power_sign * iac_peak_a * math.sin(theta - phi_rad)
        state = _tcm_cycle_state(
            avg_a=avg,
            vac_v=vac,
            vdc_v=vdc_v,
            inductance_h=inductance_h,
            irev_abs_a=irev_abs_a,
            vac_floor_v=vac_floor_v,
            fsw_min_hz=fsw_min_hz,
        )
        _append_tcm_detail_sample(
            time_s,
            current_a,
            iavg_a,
            ipeak_envelope_a,
            ivalley_envelope_a,
            fsw_hz,
            natural_fsw_hz,
            mixed_mode_clamped,
            final_t,
            float(state["valley_signed_a"]),
            avg,
            float(state["peak_signed_a"]),
            float(state["valley_signed_a"]),
            float(state["fsw_hz"]),
            float(state["natural_fsw_hz"]),
            bool(state["mixed_mode_clamped"]),
        )

    downsampled = False
    if len(time_s) > max_points:
        indices = _downsample_indices(len(time_s), max_points)
        time_s = [time_s[index] for index in indices]
        current_a = [current_a[index] for index in indices]
        iavg_a = [iavg_a[index] for index in indices]
        ipeak_envelope_a = [ipeak_envelope_a[index] for index in indices]
        ivalley_envelope_a = [ivalley_envelope_a[index] for index in indices]
        fsw_hz = [fsw_hz[index] for index in indices]
        natural_fsw_hz = [natural_fsw_hz[index] for index in indices]
        mixed_mode_clamped = [mixed_mode_clamped[index] for index in indices]
        downsampled = True

    return {
        "time_s": time_s,
        "inductor_current_a": current_a,
        "iavg_a": iavg_a,
        "ipeak_envelope_a": ipeak_envelope_a,
        "ivalley_envelope_a": ivalley_envelope_a,
        "fsw_hz": fsw_hz,
        "natural_fsw_hz": natural_fsw_hz,
        "mixed_mode_clamped": mixed_mode_clamped,
        "cycle_start_time_s": cycle_start_time_s,
        "cycle_fsw_hz": cycle_fsw_hz,
        "cycle_natural_fsw_hz": cycle_natural_fsw_hz,
        "cycle_mixed_mode_clamped": cycle_mixed_mode_clamped,
        "sample_count": len(time_s),
        "cycle_count": cycle_count,
        "mixed_mode_cycle_count": sum(1 for value in cycle_mixed_mode_clamped if value),
        "downsampled": downsampled,
        "samples_per_tcm_cycle": samples_per_cycle,
    }


def _append_tcm_detail_sample(
    time_s: list[float],
    current_a: list[float],
    iavg_a: list[float],
    ipeak_envelope_a: list[float],
    ivalley_envelope_a: list[float],
    fsw_hz: list[float],
    natural_fsw_hz: list[float],
    mixed_mode_clamped: list[bool],
    sample_t_s: float,
    sample_i_a: float,
    avg_a: float,
    peak_a: float,
    valley_a: float,
    cycle_fsw_hz: float,
    cycle_natural_fsw_hz: float,
    cycle_mixed_mode_clamped: bool,
) -> None:
    if time_s and sample_t_s <= time_s[-1]:
        sample_t_s = time_s[-1] + 1e-12
    time_s.append(sample_t_s)
    current_a.append(sample_i_a)
    iavg_a.append(avg_a)
    ipeak_envelope_a.append(peak_a)
    ivalley_envelope_a.append(valley_a)
    fsw_hz.append(cycle_fsw_hz)
    natural_fsw_hz.append(cycle_natural_fsw_hz)
    mixed_mode_clamped.append(cycle_mixed_mode_clamped)


def _build_tcm_dc_link_capacitor_current_detail(
    *,
    detail_time_s: list[float],
    detail_inductor_current_a: list[float],
    vac_peak_v: float,
    f_line_hz: float,
    idc_avg_a: float,
    vdc_v: float,
) -> dict[str, object]:
    """Return first-pass TCM DC-link capacitor current for capacitor selection."""

    sample_count = min(len(detail_time_s), len(detail_inductor_current_a))
    time_s = detail_time_s[:sample_count]
    current_a: list[float] = []
    for t_s, il_a in zip(time_s, detail_inductor_current_a[:sample_count]):
        theta = 2.0 * math.pi * f_line_hz * t_s
        vac_v = vac_peak_v * math.sin(theta)
        pac_w = vac_v * il_a
        idc_inst_a = pac_w / max(vdc_v, 1e-12)
        current_a.append(idc_avg_a - idc_inst_a)
    current_a = _remove_average(current_a)
    return {
        "time_s": time_s,
        "current_a": current_a,
        "rms_a": _rms(current_a),
        "basis": "TCM detailed instantaneous-power DC-link current, first-pass RMS basis",
    }


def _downsample_indices(length: int, max_points: int) -> list[int]:
    if length <= max_points:
        return list(range(length))
    if max_points <= 1:
        return [0]
    return sorted({round(index * (length - 1) / (max_points - 1)) for index in range(max_points)})


def _tcm_low_slope_diagnostic(detail: dict[str, object], *, fsw_min_hz: float) -> dict[str, object]:
    cycle_fsw = [float(value) for value in detail.get("cycle_natural_fsw_hz", []) if float(value) > 0.0]
    clamped_cycles = [bool(value) for value in detail.get("cycle_mixed_mode_clamped", [])]
    cycle_start = [float(value) for value in detail.get("cycle_start_time_s", [])]
    if not cycle_fsw or fsw_min_hz <= 0.0:
        return {
            "low_slope_region_detected": False,
            "fsw_min_limit_hz": fsw_min_hz,
            "min_fsw_hz": min(cycle_fsw) if cycle_fsw else None,
            "min_fsw_time_s": None,
            "violation_count": 0,
            "cycle_count": len(cycle_fsw),
            "violation_fraction": 0.0,
            "mixed_mode_pending": False,
            "mixed_mode_fallback_active": False,
        }
    threshold_hz = fsw_min_hz * TCM_LOW_SLOPE_FSW_TOLERANCE
    violations = [index for index, value in enumerate(cycle_fsw) if value < threshold_hz]
    clamped_count = sum(1 for value in clamped_cycles if value)
    min_index, min_fsw = min(enumerate(cycle_fsw), key=lambda item: item[1])
    return {
        "low_slope_region_detected": bool(violations),
        "fsw_min_limit_hz": fsw_min_hz,
        "min_fsw_hz": min_fsw,
        "min_fsw_time_s": cycle_start[min_index] if min_index < len(cycle_start) else None,
        "violation_count": len(violations),
        "cycle_count": len(cycle_fsw),
        "violation_fraction": len(violations) / max(len(cycle_fsw), 1),
        "mixed_mode_pending": False,
        "mixed_mode_fallback_active": clamped_count > 0,
    }


def _tcm_cycle_state(
    *,
    avg_a: float,
    vac_v: float,
    vdc_v: float,
    inductance_h: float,
    irev_abs_a: float,
    vac_floor_v: float,
    fsw_min_hz: float,
) -> dict[str, float | bool]:
    direction = _sign(avg_a) or _sign(vac_v) or 1
    avg_abs = abs(avg_a)
    natural_peak_abs = 2.0 * avg_abs + irev_abs_a
    natural_delta = natural_peak_abs + irev_abs_a
    vac_eff = min(max(abs(vac_v), vac_floor_v), 0.98 * vdc_v)
    a_factor = 1.0 / max(vdc_v - vac_eff, 1e-12) + 1.0 / max(vac_eff, 1e-12)
    natural_period_s = inductance_h * natural_delta * a_factor
    natural_fsw_hz = 1.0 / max(natural_period_s, 1e-12)
    mixed_mode_clamped = fsw_min_hz > 0.0 and natural_fsw_hz < fsw_min_hz * TCM_LOW_SLOPE_FSW_TOLERANCE
    if mixed_mode_clamped:
        switching_period_s = 1.0 / fsw_min_hz
        delta = switching_period_s / max(inductance_h * a_factor, 1e-12)
        peak_signed = avg_a + 0.5 * direction * delta
        valley_signed = avg_a - 0.5 * direction * delta
        fsw_hz = fsw_min_hz
    else:
        delta = natural_delta
        peak_signed = direction * natural_peak_abs
        valley_signed = -direction * irev_abs_a
        switching_period_s = natural_period_s
        fsw_hz = natural_fsw_hz
    t_up_s = inductance_h * delta / max(vdc_v - vac_eff, 1e-12)
    t_down_s = inductance_h * delta / max(vac_eff, 1e-12)
    return {
        "peak_signed_a": peak_signed,
        "valley_signed_a": valley_signed,
        "delta_i_a": abs(peak_signed - valley_signed),
        "t_up_s": t_up_s,
        "t_down_s": t_down_s,
        "switching_period_s": t_up_s + t_down_s,
        "fsw_hz": fsw_hz,
        "natural_fsw_hz": natural_fsw_hz,
        "mixed_mode_clamped": mixed_mode_clamped,
    }


def _build_refined_unipolar_spwm_waveforms(
    *,
    vdc_v: float,
    vac_peak_v: float,
    iac_peak_a: float,
    power_factor: float,
    f_line_hz: float,
    fsw_hz: float,
    inductance_h: float,
    capacitance_f: float,
    idc_avg_a: float,
    low_frequency_time_s: list[float],
    low_frequency_vdc_v: list[float],
) -> dict[str, object]:
    period_s = 1.0 / max(f_line_hz, 1e-12)
    switching_cycles = max(int(round(fsw_hz / max(f_line_hz, 1e-12))), 1)
    samples_per_switching_period = 12
    sample_count = switching_cycles * samples_per_switching_period
    modulation_index = vac_peak_v / max(vdc_v, 1e-12)
    phi_rad = _current_phase_rad(power_factor)
    active_power_sign = _active_power_sign(power_factor)

    time_s: list[float] = []
    carrier: list[float] = []
    mod_a: list[float] = []
    mod_b: list[float] = []
    gate_s1: list[float] = []
    gate_s2: list[float] = []
    gate_s3: list[float] = []
    gate_s4: list[float] = []
    bridge_state: list[float] = []
    v_ab_pwm_v: list[float] = []
    vac_fundamental_v: list[float] = []
    i_ac_fundamental_a: list[float] = []
    vdc_link_v: list[float] = []

    for index in range(sample_count + 1):
        t_s = period_s * index / sample_count
        theta = 2.0 * math.pi * f_line_hz * t_s
        normalized_carrier = _triangular_carrier((t_s * fsw_hz) % 1.0)
        ma = modulation_index * math.sin(theta)
        mb = -ma
        s1 = 1.0 if ma >= normalized_carrier else 0.0
        s3 = 1.0 if mb >= normalized_carrier else 0.0
        state = s1 - s3
        vdc_inst_v = _interp_periodic(low_frequency_time_s, low_frequency_vdc_v, t_s)

        time_s.append(t_s)
        carrier.append(normalized_carrier)
        mod_a.append(ma)
        mod_b.append(mb)
        gate_s1.append(s1)
        gate_s2.append(1.0 - s1)
        gate_s3.append(s3)
        gate_s4.append(1.0 - s3)
        bridge_state.append(state)
        v_ab_pwm_v.append(state * vdc_inst_v)
        vac_fundamental_v.append(vac_peak_v * math.sin(theta))
        i_ac_fundamental_a.append(active_power_sign * iac_peak_a * math.sin(theta - phi_rad))
        vdc_link_v.append(vdc_inst_v)

    inductor_ripple_a = _integrate_pwm_inductor_ripple_by_cycle(
        time_s,
        v_ab_pwm_v,
        vac_fundamental_v,
        inductance_h,
        samples_per_switching_period,
    )
    inductor_current_a = [fundamental + ripple for fundamental, ripple in zip(i_ac_fundamental_a, inductor_ripple_a, strict=True)]
    local_ripple_pp_a = _local_cycle_peak_to_peak(inductor_ripple_a, samples_per_switching_period)
    dc_link_current_a = [state * current for state, current in zip(bridge_state, inductor_current_a, strict=True)]
    dc_link_cap_current_pwm_a = [idc_avg_a - current for current in dc_link_current_a]
    dc_link_cap_current_pwm_a = _remove_average(dc_link_cap_current_pwm_a)
    dc_link_pwm_ripple_v = _integrate_periodic_capacitor_voltage(time_s, dc_link_cap_current_pwm_a, capacitance_f)

    branch_current_metrics = _branch_current_metrics(
        inductor_current_a,
        {
            "s1": gate_s1,
            "s2": gate_s2,
            "s3": gate_s3,
            "s4": gate_s4,
        },
    )
    return {
        "time_s": time_s,
        "carrier": carrier,
        "mod_a": mod_a,
        "mod_b": mod_b,
        "gate_s1": gate_s1,
        "gate_s2": gate_s2,
        "gate_s3": gate_s3,
        "gate_s4": gate_s4,
        "bridge_state": bridge_state,
        "v_ab_pwm_v": v_ab_pwm_v,
        "vac_fundamental_v": vac_fundamental_v,
        "i_ac_fundamental_a": i_ac_fundamental_a,
        "inductor_ripple_a": inductor_ripple_a,
        "inductor_current_a": inductor_current_a,
        "dc_link_current_a": dc_link_current_a,
        "dc_link_capacitor_current_pwm_a": dc_link_cap_current_pwm_a,
        "dc_link_voltage_v": vdc_link_v,
        "dc_link_voltage_pwm_ripple_v": dc_link_pwm_ripple_v,
        "samples_per_switching_period": samples_per_switching_period,
        "switching_cycle_count": switching_cycles,
        "bridge_voltage_levels_v": [-vdc_v, 0.0, vdc_v],
        "inductor_pwm_ripple_pp_a": max(local_ripple_pp_a) if local_ripple_pp_a else 0.0,
        "inductor_pwm_ripple_mean_local_pp_a": _mean(local_ripple_pp_a),
        "inductor_pwm_ripple_local_pp_rms_a": _rms(local_ripple_pp_a),
        "branch_current_metrics": branch_current_metrics,
        "dc_link_capacitor_current_pwm_rms_a": _rms(dc_link_cap_current_pwm_a),
        "dc_link_voltage_pwm_ripple_pp_v": max(dc_link_pwm_ripple_v) - min(dc_link_pwm_ripple_v) if dc_link_pwm_ripple_v else 0.0,
        "notes": [
            "Unipolar SPWM preview uses ideal complementary gates without dead-time.",
            "Bridge voltage is generated from two sinusoidal references compared with a triangular carrier.",
            "Inductor PWM ripple is integrated from v_L = v_ab_pwm - v_ac,fundamental.",
            "DC-link PWM capacitor current is provided for waveform inspection only; capacitor bank selection still uses the low-frequency energy-balance current.",
        ],
    }


def _local_cycle_peak_to_peak(values: list[float], samples_per_switching_period: int) -> list[float]:
    if not values or samples_per_switching_period <= 1:
        return []
    cycle_count = (len(values) - 1) // samples_per_switching_period
    spans: list[float] = []
    for cycle in range(cycle_count):
        start = cycle * samples_per_switching_period
        end = min(start + samples_per_switching_period + 1, len(values))
        chunk = values[start:end]
        if len(chunk) >= 3:
            spans.append(max(chunk) - min(chunk))
    return spans


def _branch_current_metrics(
    inductor_current_a: list[float],
    gates: dict[str, list[float]],
) -> dict[str, object]:
    metrics: dict[str, object] = {
        "semantics": "complete_mosfet_with_antiparallel_diode_branch_current",
        "current_split_status": "mosfet_channel_and_diode_not_separately_instrumented",
    }
    for role, gate in gates.items():
        branch = [current if command >= 0.5 else 0.0 for current, command in zip(inductor_current_a, gate, strict=True)]
        metrics[role] = {
            "average_absolute_current_a": _mean([abs(value) for value in branch]),
            "rms_current_a": _rms(branch),
            "peak_absolute_current_a": max((abs(value) for value in branch), default=0.0),
        }
    return metrics


def _clamp_load_ratio(value: float) -> float:
    try:
        return min(max(float(value), 0.0), 1.0)
    except (TypeError, ValueError):
        return 1.0


def _operating_power_factor(operating_point: OperatingPoint | None, design_power_factor: float) -> float:
    raw_value = design_power_factor
    if operating_point is not None and operating_point.power_factor is not None:
        raw_value = operating_point.power_factor
    try:
        return min(max(float(raw_value), -1.0), 1.0)
    except (TypeError, ValueError):
        return min(max(float(design_power_factor), -1.0), 1.0)


def _power_factor_abs_for_current(power_factor: float) -> float:
    return max(abs(float(power_factor)), 1e-6)


def _current_phase_rad(power_factor: float) -> float:
    return math.acos(min(max(_power_factor_abs_for_current(power_factor), 0.0), 1.0))


def _active_power_sign(power_factor: float) -> float:
    return -1.0 if float(power_factor) < 0.0 else 1.0


def _sign(value: float) -> int:
    if value > 1e-12:
        return 1
    if value < -1e-12:
        return -1
    return 0


def _triangular_carrier(phase: float) -> float:
    phase = phase % 1.0
    if phase < 0.5:
        return -1.0 + 4.0 * phase
    return 3.0 - 4.0 * phase


def _integrate_pwm_inductor_ripple_by_cycle(
    time_s: list[float],
    bridge_voltage_v: list[float],
    ac_fundamental_v: list[float],
    inductance_h: float,
    samples_per_switching_period: int,
) -> list[float]:
    if (
        len(time_s) != len(bridge_voltage_v)
        or len(time_s) != len(ac_fundamental_v)
        or len(time_s) < 2
        or inductance_h <= 0.0
        or samples_per_switching_period <= 1
    ):
        return [0.0 for _ in time_s]
    ripple = [0.0 for _ in time_s]
    cycle_count = (len(time_s) - 1) // samples_per_switching_period
    for cycle in range(cycle_count):
        start = cycle * samples_per_switching_period
        end = min(start + samples_per_switching_period, len(time_s) - 1)
        local = [0.0]
        for index in range(start + 1, end + 1):
            dt_s = time_s[index] - time_s[index - 1]
            v_l_prev = bridge_voltage_v[index - 1] - ac_fundamental_v[index - 1]
            v_l_now = bridge_voltage_v[index] - ac_fundamental_v[index]
            local.append(local[-1] + 0.5 * (v_l_prev + v_l_now) * dt_s / inductance_h)
        drift_a = local[-1] - local[0]
        span = len(local) - 1
        if span > 0:
            local = [value - drift_a * offset / span for offset, value in enumerate(local)]
        mean_a = sum(local) / len(local)
        local = [value - mean_a for value in local]
        for offset, value in enumerate(local):
            ripple[start + offset] = value
    if ripple:
        ripple[-1] = ripple[0]
    return ripple


def _integrate_periodic_capacitor_voltage(time_s: list[float], current_a: list[float], capacitance_f: float) -> list[float]:
    if len(time_s) != len(current_a) or len(time_s) < 2 or capacitance_f <= 0.0:
        return [0.0 for _ in current_a]
    ripple = [0.0]
    for index in range(1, len(time_s)):
        dt_s = time_s[index] - time_s[index - 1]
        avg_current_a = 0.5 * (current_a[index - 1] + current_a[index])
        ripple.append(ripple[-1] + avg_current_a * dt_s / capacitance_f)
    drift_v = ripple[-1] - ripple[0]
    span = len(ripple) - 1
    if span > 0:
        ripple = [value - drift_v * index / span for index, value in enumerate(ripple)]
    mean_v = sum(ripple) / len(ripple)
    return [value - mean_v for value in ripple]


def _interp_periodic(time_s: list[float], values: list[float], query_s: float) -> float:
    if len(time_s) != len(values) or not time_s:
        return 0.0
    if len(time_s) == 1:
        return float(values[0])
    period_s = time_s[-1] - time_s[0]
    if period_s <= 0.0:
        return float(values[0])
    wrapped_s = ((query_s - time_s[0]) % period_s) + time_s[0]
    dt_s = time_s[1] - time_s[0]
    if dt_s <= 0.0:
        return float(values[0])
    raw_index = (wrapped_s - time_s[0]) / dt_s
    index = int(math.floor(raw_index))
    if index >= len(values) - 1:
        return float(values[-1])
    frac = raw_index - index
    return float(values[index]) * (1.0 - frac) + float(values[index + 1]) * frac


def _unique_sorted(values: list[float]) -> list[float]:
    rounded = sorted({round(float(value), 9) for value in values})
    return [float(value) for value in rounded]


def _rms(values: list[float]) -> float:
    if not values:
        return 0.0
    return math.sqrt(sum(value * value for value in values) / len(values))


def _mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def _remove_average(values: list[float]) -> list[float]:
    if not values:
        return []
    average = sum(values) / len(values)
    return [value - average for value in values]
