"""Magnetics engine helpers."""

from .core_loss_kernel import (
    MaterialLossModelSelection,
    calculate_core_loss,
    calculate_igse_loss,
    calculate_steinmetz_loss,
    select_steinmetz_coefficients,
    select_steinmetz_model,
    steinmetz_loss_density_w_per_m3,
)
from .core_loss_evaluation_context import (
    FUNDAMENTAL_EXTRACTION_METHOD,
    build_core_loss_evaluation_context,
    extract_fundamental_flux_amplitude_t,
)
from .core_loss_model_coverage import (
    CoreLossMethodSpecification,
    METHOD_SPECIFICATIONS,
    STEP7A_COVERAGE_CONTRACT_VERSION,
    assess_material_loss_coverage,
    summarize_material_loss_coverage,
)
from .core_loss_proprietary_models import (
    MAGNETICS_FORMULA_ID,
    MICROMETALS_FORMULA_ID,
    POCO_FORMULA_ID,
    STEP7B_MODEL_POLICY,
    TDG_FORMULA_ID,
    calculate_magnetics_loss,
    calculate_micrometals_loss,
    calculate_poco_loss,
    calculate_proprietary_volumetric_loss,
    calculate_tdg_loss,
)
from .core_loss_loss_factor import (
    InitialPermeabilityResolution,
    LossFactorInterpolation,
    INTERPOLATION_POLICY,
    LOSS_FACTOR_FORMULA_ID,
    STEP7D_MODEL_POLICY,
    calculate_loss_factor_loss,
    interpolate_loss_factor,
    loss_factor_cache_key,
    resolve_initial_permeability,
)
from .core_loss_roshen import (
    ROSHEN_FORMULA_ID,
    ROSHEN_H_FIELD_STEP_A_PER_M,
    RoshenPropertyResolution,
    STEP7E_MODEL_POLICY,
    calculate_roshen_loss,
    resolve_roshen_property,
)
from .core_loss_magnetec import (
    MAGNETEC_FORMULA_ID,
    STEP7F_MODEL_POLICY,
    calculate_magnetec_loss,
)
from .core_loss_measured import (
    INTERPOLATION_SPACE,
    MEASURED_FORMULA_ID,
    STEP7G_MEASURED_MODEL_POLICY,
    evaluate_measured_loss,
)
from .core_loss_router import (
    ROUTER_POLICY,
    ROUTER_SHADOW_POLICY,
    legacy_material_v2,
    route_core_loss,
    route_core_loss_from_build_result,
    route_legacy_steinmetz_loss,
)
from .core_loss_golden_reference import (
    CoreLossGoldenReference,
    PhysicalValidationIssue,
    PhysicalValidationReport,
    validate_core_loss_result,
    validate_golden_reference,
)

__all__ = [
    "MaterialLossModelSelection",
    "calculate_core_loss",
    "calculate_igse_loss",
    "calculate_steinmetz_loss",
    "select_steinmetz_coefficients",
    "select_steinmetz_model",
    "steinmetz_loss_density_w_per_m3",
    "FUNDAMENTAL_EXTRACTION_METHOD",
    "build_core_loss_evaluation_context",
    "extract_fundamental_flux_amplitude_t",
    "CoreLossMethodSpecification",
    "METHOD_SPECIFICATIONS",
    "STEP7A_COVERAGE_CONTRACT_VERSION",
    "assess_material_loss_coverage",
    "summarize_material_loss_coverage",
    "MAGNETICS_FORMULA_ID",
    "MICROMETALS_FORMULA_ID",
    "POCO_FORMULA_ID",
    "STEP7B_MODEL_POLICY",
    "TDG_FORMULA_ID",
    "calculate_magnetics_loss",
    "calculate_micrometals_loss",
    "calculate_poco_loss",
    "calculate_proprietary_volumetric_loss",
    "calculate_tdg_loss",
    "InitialPermeabilityResolution",
    "LossFactorInterpolation",
    "INTERPOLATION_POLICY",
    "LOSS_FACTOR_FORMULA_ID",
    "STEP7D_MODEL_POLICY",
    "calculate_loss_factor_loss",
    "interpolate_loss_factor",
    "loss_factor_cache_key",
    "resolve_initial_permeability",
    "ROSHEN_FORMULA_ID",
    "ROSHEN_H_FIELD_STEP_A_PER_M",
    "RoshenPropertyResolution",
    "STEP7E_MODEL_POLICY",
    "calculate_roshen_loss",
    "resolve_roshen_property",
    "MAGNETEC_FORMULA_ID",
    "STEP7F_MODEL_POLICY",
    "calculate_magnetec_loss",
    "INTERPOLATION_SPACE",
    "MEASURED_FORMULA_ID",
    "STEP7G_MEASURED_MODEL_POLICY",
    "evaluate_measured_loss",
    "ROUTER_POLICY",
    "ROUTER_SHADOW_POLICY",
    "route_core_loss",
    "route_core_loss_from_build_result",
    "route_legacy_steinmetz_loss",
    "legacy_material_v2",
    "CoreLossGoldenReference",
    "PhysicalValidationIssue",
    "PhysicalValidationReport",
    "validate_core_loss_result",
    "validate_golden_reference",
]
