"""First-pass synthesis for a three-phase two-level voltage-source inverter."""

from __future__ import annotations

import math

from ...base.candidate import TopologyCandidate
from ...base.spec import TopologySpec


def calculate_three_phase_two_level_voltage_source_inverter(
    *,
    vdc_nom_v: float,
    vac_ll_rms_v: float,
    fsw_hz: float,
    pout_w: float,
    power_factor: float,
    inductor_current_ripple_ratio: float,
    dc_link_voltage_ripple_ratio: float,
) -> dict[str, float | str | bool | int]:
    """Return CCM fixed-frequency SPWM first-pass inverter estimates."""

    vac_phase_rms_v = vac_ll_rms_v / math.sqrt(3.0)
    vac_phase_peak_v = math.sqrt(2.0) * vac_phase_rms_v
    i_phase_rms_a = pout_w / (math.sqrt(3.0) * vac_ll_rms_v * power_factor)
    i_phase_peak_a = math.sqrt(2.0) * i_phase_rms_a
    modulation_index = 2.0 * vac_phase_peak_v / vdc_nom_v
    delta_il_pp_a = inductor_current_ripple_ratio * i_phase_peak_a
    l_phase_h = vdc_nom_v / (8.0 * fsw_hz * delta_il_pp_a)
    delta_vdc_pp_v = dc_link_voltage_ripple_ratio * vdc_nom_v
    idc_avg_a = pout_w / vdc_nom_v
    cdc_required_f = idc_avg_a / (fsw_hz * delta_vdc_pp_v)
    ccm_valid = delta_il_pp_a < 2.0 * i_phase_peak_a
    return {
        "vac_phase_rms_v": vac_phase_rms_v,
        "vac_phase_peak_v": vac_phase_peak_v,
        "i_phase_rms_a": i_phase_rms_a,
        "i_phase_peak_a": i_phase_peak_a,
        "modulation_index": modulation_index,
        "modulation_limit": 1.0,
        "modulation_valid": modulation_index <= 1.0,
        "delta_il_pp_a": delta_il_pp_a,
        "inductor_ripple_design_target_pp_a": delta_il_pp_a,
        "inductor_ripple_design_target_ratio": inductor_current_ripple_ratio,
        "inductor_ripple_design_target_definition": "sizing target; not predicted achieved SPWM ripple",
        "l_phase_h": l_phase_h,
        "delta_vdc_pp_v": delta_vdc_pp_v,
        "cdc_required_f": cdc_required_f,
        "idc_avg_a": idc_avg_a,
        "ccm_valid": ccm_valid,
        "phase_count": 3,
        "switch_position_count": 6,
        "inductor_basis": "L_phase = Vdc / (8 * fsw * delta_i_target_pp), conservative sizing target",
        "dc_link_capacitor_basis": "Cdc = Idc_avg / (fsw * delta_vdc_pp), three-phase first-pass ripple proxy",
    }


def synthesize(spec: TopologySpec) -> TopologyCandidate:
    """Build a first-pass three-phase inverter topology candidate."""

    metadata = dict(spec.metadata)
    estimates = calculate_three_phase_two_level_voltage_source_inverter(
        vdc_nom_v=float(metadata["vdc_nom_v"]),
        vac_ll_rms_v=float(metadata["vac_ll_rms_v"]),
        fsw_hz=float(metadata["fsw_hz"]),
        pout_w=spec.pout,
        power_factor=float(metadata["power_factor"]),
        inductor_current_ripple_ratio=float(metadata["inductor_current_ripple_ratio"]),
        dc_link_voltage_ripple_ratio=float(metadata["dc_link_voltage_ripple_ratio"]),
    )
    candidate_metadata = {**metadata, **estimates}
    phase_peak_a = float(estimates["i_phase_peak_a"])
    delta_il_pp_a = float(estimates["delta_il_pp_a"])
    return TopologyCandidate(
        topology_id=spec.topology_id,
        display_name=spec.display_name,
        vin_min=float(metadata["vdc_nom_v"]),
        vin_max=float(metadata["vdc_nom_v"]),
        vin_nom=float(metadata["vdc_nom_v"]),
        vout_target=float(metadata["vac_ll_rms_v"]),
        pout_target=spec.pout,
        duty_nom=0.5,
        iout=float(estimates["i_phase_rms_a"]),
        fs_hz=float(metadata["fsw_hz"]),
        inductance_h=float(estimates["l_phase_h"]),
        capacitance_f=float(estimates["cdc_required_f"]),
        delta_il=delta_il_pp_a,
        delta_vo=float(estimates["delta_vdc_pp_v"]),
        il_peak=phase_peak_a + 0.5 * delta_il_pp_a,
        il_valley=-phase_peak_a - 0.5 * delta_il_pp_a,
        ccm_valid=bool(estimates["ccm_valid"]),
        mode_capable="ccm_three_phase_two_level_spwm_first_pass",
        output_ripple_vpp_v=float(estimates["delta_vdc_pp_v"]),
        feasible=bool(estimates["modulation_valid"]),
        notes=[
            "First-pass three-phase two-level inverter CCM parameter synthesis.",
            "Output inductor is a per-phase inductance from a conservative current-ripple sizing target.",
            "Candidate delta_il remains the sizing target; predicted achieved SPWM ripple is generated by the waveform stage.",
            "DC-link capacitor is a first-pass three-phase switching-ripple proxy.",
        ],
        metadata=candidate_metadata,
    )
